### PR TITLE
fix: increase brute force protection TOTP

### LINKED ISSUE #522: Increase OTP bruteforce protection
Number of attempts before the OTP is regenerated is currently set to 10 => it shall be set to 5.

### PR DESCRIPTION
**Pull request by vinistevam**
# Overview

This PR aims to increase brute force protection on TOTP setting max attempts within 30 seconds to 5.

# Changes

## Common
- set max attempts within 30 seconds to `5`.

## Issues
resolves: #522

### CODE REVIEW

File: packages/common/src/utils/totp.ts [hunk 1]
```diff
@@ -1,7 +1,7 @@
 import * as OTPAuth from 'otpauth';
 import { randomHex } from './crypto';
 
-const MAX_TOTP_VALIDATE_RETRY_IN_30_SECONDS = 10;
+const MAX_TOTP_VALIDATE_RETRY_IN_30_SECONDS = 5;
```
Comment (cryptotavares) [inline packages/common/src/utils/totp.ts:4]: you could export this const and import it on the test. Just to be sure that both are always in sync

**Review by OGPoyraz — APPROVED** [review]

**Review by matthewwalsh0 — APPROVED** [review]
