### PR TITLE
fix: add app icon on dev mode

### LINKED ISSUE #567: Add app icon even when running in dev mode

### PR DESCRIPTION
**Pull request by OGPoyraz**
# Overview
Test

### CODE REVIEW

File: packages/app/src/app/ui/app-navigation.ts [hunk 1]
```diff
@@ -120,6 +120,13 @@ export default class AppNavigation {
       const dockMenuTemplate = [this.createAboutMenuItem()];
       const dockMenu = Menu.buildFromTemplate(dockMenuTemplate);
       app.dock.setMenu(dockMenu);
+
+      if (!app.isPackaged) {
+        const image = nativeImage.createFromPath(
+          path.resolve(__dirname, '../icons/icon.png'),
```
Comment (matthewwalsh0) [inline packages/app/src/app/ui/app-navigation.ts:126]: Rather than duplicate the icon, could we instead update `build.sh` to copy the icon from `packages/app/build` into `dist/app` and reference it there?

Comment (OGPoyraz) [reply packages/app/src/app/ui/app-navigation.ts:126]: Make sense, fixed.

**Review by matthewwalsh0 — APPROVED** [review]
